title: "EvanZhao's Tech Blog"
description: "Sharing knowledge about backend development, AI, and system design."
baseurl: ""  # GitHub Pages 需留空
url: "http://127.0.0.1:4000" # 你的 GitHub Pages 网址

# 主题设置
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

author:
  name: "Evan Zhao"
  avatar: "/assets/images/avatar.png" # 头像
  bio     : "I am a software engineer."
  location: "Canada"
  email: "evanzhao119@gmail.com"
  github: "EvanZhao119"
  linkedin: "evan-zhao-software"
  # twitter: "evanzhao_dev"
