title: "EvanZhao's Tech Blog"
description: "Sharing knowledge about backend development, AI, and system design."
baseurl: ""  # GitHub Pages 需留空
# url: "https://evanzhao119.github.io"  # 你的 GitHub Pages 网址
url: "http://127.0.0.1:4000" # 你的 GitHub Pages 网址

# 主题设置
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-paginate

author:
  name: "Evan Zhao"
  avatar: "/assets/images/avatar.png" # 头像
  bio     : "I am a software engineer."
  location: "Canada"
  email: "evanzhao119@gmail.com"
  github: "EvanZhao119"
  linkedin: "evan-zhao-software"
  # twitter: "evanzhao_dev"

exclude:
  - CHANGELOG.md

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-D5FXLGMCXD"
    anonymize_ip: false # true/false

# 添加分页配置
paginate: 3  # 每页显示的文章数量
paginate_path: "/java/page/:num/"  # 修改这里，设置Java分类的分页路径

# 分页配置
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - 第 :num 页'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# 分类页面配置
category_archive:
  type: liquid
  path: /
